require 'nokogiri'
time = Time.new

builder = Nokogiri::XML::Builder.new("encoding" => "UTF-8") { |xml|
    xml.opml('version' => "1.1"){
        xml.head{
            xml.title_ "Generated by OMPLBuilder: #{time}"
            xml.dateCreated_ "#{time}"
        }
        xml.body{
            
        }
    }

    #   xml.root('type' => 'default', 'xmlns:foo' => 'bar') do
    #     xml.tenderlove
    #   end
}
puts builder.to_xml
