require 'nokogiri'

=begin
Example opml file
<?xml version="1.0" encoding="utf-8" ?>
<opml version="1.1">
<head>
<title>Generated by Seyoung</title>
<dateCreated>Sat, 05 Dec 2015 11:54:16 +0100</dateCreated>
</head>
<body>
<outline title="www.hs.fi/rss/?osastot=politiikka" text="www.hs.fi/rss/?osastot=politiikka" type="rss" xmlUrl="http://www.hs.fi/rss/?osastot=politiikka" />
</body></opml>
=end

# doc = Nokogiri::XML "<root>foo</root>"
time = Time.new

title = "<title>Generated by OMPLBuilder: #{time}</title>"
dateCreated = "<dateCreated>#{time}</dateCreated></head>"
head = "<head>#{title}#{dateCreated}</head>"
doc = Nokogiri.XML("<opml version=\"1.1\">#{head}<body></body></opml>", nil, 'UTF-8')
puts doc.to_xml


outline = Nokogiri::XML::Node.new "outline", doc
puts doc.to_xml
outline.content = "title=\"Rattijuoppo löi ja potki – poliisi käytti etälamautinta Imatralla\" text=\"Rattijuoppo löi ja potki – poliisi käytti etälamautinta Imatralla\" type=\"application/rss+xml\" xmlUrl=\"http://www.hs.fi/kotimaa/a1449892319617\""
doc.children.after(outline)
puts doc.to_xml


# pi = Nokogiri::XML::ProcessingInstruction.new(doc, "xml-stylesheet", 'type="text/xsl" href="foo.xsl"')
# doc.root.add_previous_sibling pi
# doc.to_xml
# => "<?xml version=\"1.0\"?>
# <?xml-stylesheet type=\"text/xsl\" href=\"foo.xsl\"?>
# <root>foo</root>
# "
