#!/usr/bin/ruby -w

=begin
<?xml version="1.0" encoding="utf-8" ?>
<opml version="1.1">
<head>
<title>Generated by Seyoung</title>
<dateCreated>Sat, 05 Dec 2015 11:54:16 +0100</dateCreated>
</head>
<body>
<outline title="www.hs.fi/rss/?osastot=politiikka" text="www.hs.fi/rss/?osastot=politiikka" type="rss" xmlUrl="http://www.hs.fi/rss/?osastot=politiikka" />
</body></opml>
=end
require 'feedjira'

url_hs = "www.hs.fi/rss/?osastot=politiikka"
feed_hs = Feedjira::Feed.fetch_and_parse url_hs

puts feed_hs.title
